USE [master]
GO

/****** Object:  Database [hospedaria]    Script Date: 10/29/2017 5:34:18 PM ******/
DROP DATABASE [hospedaria]
GO

/****** Object:  Database [hospedaria]    Script Date: 10/29/2017 5:34:18 PM ******/
CREATE DATABASE [hospedaria]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'hospedaria', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\hospedaria.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'hospedaria_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\hospedaria_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [hospedaria] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [hospedaria].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [hospedaria] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [hospedaria] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [hospedaria] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [hospedaria] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [hospedaria] SET ARITHABORT OFF 
GO

ALTER DATABASE [hospedaria] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [hospedaria] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [hospedaria] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [hospedaria] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [hospedaria] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [hospedaria] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [hospedaria] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [hospedaria] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [hospedaria] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [hospedaria] SET  DISABLE_BROKER 
GO

ALTER DATABASE [hospedaria] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [hospedaria] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [hospedaria] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [hospedaria] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [hospedaria] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [hospedaria] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [hospedaria] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [hospedaria] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [hospedaria] SET  MULTI_USER 
GO

ALTER DATABASE [hospedaria] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [hospedaria] SET DB_CHAINING OFF 
GO

ALTER DATABASE [hospedaria] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [hospedaria] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [hospedaria] SET  READ_WRITE 
GO

